import streamlit as st
import pandas as pd
from datetime import datetime, timedelta

WINDOW_DAYS = 28
TODAY = datetime.utcnow()


# ---------- DATA LOADING ----------

def load_rumor_data():
    """
    Read the CSV generated by scrape_trade_rumors.py.
    Expected columns:
    - player
    - slug
    - date
    - title
    - url
    """
    df = pd.read_csv("trade_rumors.csv")
    df["date"] = pd.to_datetime(df["date"])
    return df


# ---------- SCORING ----------

def compute_scores(df: pd.DataFrame) -> pd.DataFrame:
    """
    1 point:   last 7 days
    0.5 point: days 8–14
    0.25 point: days 15–28
    """
    df = df.copy()
    df["days_ago"] = (TODAY - df["date"]).dt.days

    def weight_for_days_ago(d):
        if 0 <= d <= 7:
            return 1.0
        elif 8 <= d <= 14:
            return 0.5
        elif 15 <= d <= 28:
            return 0.25
        else:
            return 0.0

    df["weight"] = df["days_ago"].apply(weight_for_days_ago)
    recent = df[df["days_ago"] <= WINDOW_DAYS]

    scores = (
        recent.groupby(["player", "slug"])["weight"]
        .sum()
        .reset_index()
    )
    scores.rename(columns={"weight": "trade_rumor_score"}, inplace=True)

    def count_in_range(lo, hi):
        mask = (df["days_ago"] >= lo) & (df["days_ago"] <= hi)
        return (
            df[mask]
            .groupby(["player", "slug"])["date"]
            .count()
            .rename(f"count_{lo}_{hi}")
        )

    last7 = count_in_range(0, 7)
    prev7 = count_in_range(8, 14)
    prev14 = count_in_range(15, 28)

    scores = scores.merge(last7, on=["player", "slug"], how="left")
    scores = scores.merge(prev7, on=["player", "slug"], how="left")
    scores = scores.merge(prev14, on=["player", "slug"], how="left")

    for col in ["count_0_7", "count_8_14", "count_15_28"]:
        scores[col] = scores[col].fillna(0).astype(int)

    scores = scores.sort_values("trade_rumor_score", ascending=False).reset_index(drop=True)
    scores["rank"] = scores.index + 1

    return scores


# ---------- UI HELPERS ----------

def show_rankings(df_scores: pd.DataFrame):
    st.title("NBA Trade Rumor Heat Index")

    st.write(
        "Rankings based on how often players appear in trade rumors over the last 28 days, "
        "with recent mentions weighted more heavily:\n"
        "- 1 point per mention in the last 7 days\n"
        "- 0.5 points per mention 8–14 days ago\n"
        "- 0.25 points per mention 15–28 days ago"
    )

    search = st.text_input("Search for a player")

    scores = df_scores.copy()
    if search:
        scores = scores[scores["player"].str.contains(search, case=False)]

    # Dropdown to jump to a player page
    all_players = sorted(df_scores["player"].unique())
    chosen = st.selectbox("Jump to a player page", [""] + all_players)
    if chosen:
        slug = df_scores[df_scores["player"] == chosen]["slug"].iloc[0]
        st.experimental_set_query_params(player=slug)
        st.experimental_rerun()

    display = scores[
        [
            "rank",
            "player",
            "trade_rumor_score",
            "count_0_7",
            "count_8_14",
            "count_15_28",
        ]
    ].rename(
        columns={
            "rank": "Rank",
            "player": "Player",
            "trade_rumor_score": "Score",
            "count_0_7": "Mentions (0–7d)",
            "count_8_14": "Mentions (8–14d)",
            "count_15_28": "Mentions (15–28d)",
        }
    )

    st.dataframe(display, use_container_width=True)


def show_player_view(df_all: pd.DataFrame, player_slug: str):
    player_rows = df_all[df_all["slug"] == player_slug]

    if player_rows.empty:
        st.title("Player not found")
        st.write("No trade rumors found for this player in the current data.")
        if st.button("Back to rankings"):
            st.experimental_set_query_params()
        return

    player_name = player_rows["player"].iloc[0]
    st.title(f"{player_name} – Trade Rumor Activity")

    cutoff = TODAY - timedelta(days=365)
    df_year = player_rows[player_rows["date"] >= cutoff]

    daily = (
        df_year.groupby(df_year["date"].dt.date)["player"]
        .count()
        .reset_index()
        .rename(columns={"player": "mentions", "date": "day"})
        .sort_values("day")
    )

    st.subheader("Mentions per day (last 12 months)")
    if daily.empty:
        st.write("No mentions in the last 12 months.")
    else:
        st.line_chart(daily.set_index("day")["mentions"], use_container_width=True)

    st.subheader("Most recent trade rumors")
    recent = (
        player_rows.sort_values("date", ascending=False)
        .head(30)[["date", "title", "url"]]
    )

    if recent.empty:
        st.write("No recent trade rumors for this player.")
    else:
        for _, row in recent.iterrows():
            d = row["date"].date()
            st.markdown(f"- **{d}** – [{row['title']}]({row['url']})")

    if st.button("Back to rankings"):
        st.experimental_set_query_params()


# ---------- MAIN ----------

def main():
    try:
        df_rumors = load_rumor_data()
    except FileNotFoundError:
        st.error("trade_rumors.csv not found. It will be generated automatically by the scraper workflow.")
        return

    df_scores = compute_scores(df_rumors)

    params = st.experimental_get_query_params()
    player_param = params.get("player", [None])[0]

    if player_param:
        show_player_view(df_rumors, player_param)
    else:
        show_rankings(df_scores)


if __name__ == "__main__":
    main()
